Django_level_four/template_project/basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE TEGGING

app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('other/', views.other, name='other'),
    path('relative_url_template/', views.relative_url_template, name='relative_url_template'),
]

Django_level_four/template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

Django_level_four/template_project/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'text': 'hello world',
        'text2': 'welcome',
        'number': 100
    }
    return render(request, 'basic_app/index.html', context)


def other(request):
	return render(request,'basic_app/other.html')


def relative_url_template(request):
	return render(request,'basic_app/relative_url_template.html')

Django_level_four/template_project/templates/basic_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Base File</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>Base Html File</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
    <a class="navbar-brand" href="#">Template Inhertiance</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{%url 'basic_app:index'%}">index page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{%url 'basic_app:other'%}">other page</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{%url 'admin:index'%}">ADdmin</a></li>
            <li><a class="dropdown-item" href="{%url 'basic_app:relative_url_template'%}">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="container">
      {%block body-block%}
      <!-- <--Anything outside of this will be inherted if you extend--> -->
      {%endblock%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

Django_level_four/template_project/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% load my_extras %}

{% block body_block %}
  <h1>WELCOME TO INDEX </h1>
  <h2>This is index.html page showing</h2>
  <h1>{{text2|upper}}</h1>
  <h1>{{text|cut:'hello'}}</h1>
  <h1>{{number|add:'99'}}</h1>
{% endblock %}

Django_level_four/template_project/templates/basic_app/other.html
{%extends "basic_app/base.html"%}
  {%block body_block%}
  <h1>WELCOME TO OTHER!</h1>
  <h2>Example of Template Inheritence</h2>
  {%endblock%}

Django_level_four/template_project/templates/basic_app/relative_url_template.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <h1>WELCOME TO URL RELATIVE TEMPALTE!</h1>
    <a href="{%url 'basic_app:other' %}"> THE OTHER PAGE</a>
    <a href="{%url 'admin:index' %}"> LINK TO ADMIN </a>
    <a href="{%url 'basic_app:index' %}"> THE INDEX PAGE</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>